### ISSUE TITLE
Channel Info Line Height too small

### ISSUE THREAD

**Issue by TomS2** [Scrounger/MetrixReloaded#1]
When displaying the channel info under "Menu -> Information -> Channel" characters like g, y or j will be cut off underneath the line base. Please see screenshot attached ("Auflösung").

![KanalinfoZeilenhöhe](https://user-images.githubusercontent.com/10003021/55940491-86c17b00-5c40-11e9-95d4-ba6d247601a7.jpg)

**Comment by Scrounger** [comment]
fixed in b18075bc1ae85c4fb5184a35ce44c2a87d0fe72f
