### ISSUE TITLE
image on second infobar

### ISSUE THREAD

**Issue by ycf83** [Scrounger/MetrixReloaded#3]
Hi dude, i like your great work , im about making new skin for openvision image based on openpli, which file i need to show this image of event in second infobar , 
thanks.

**Comment by Scrounger** [comment]
which image? Please show a screenshot

**Comment by ycf83** [comment]
Thanks for replay, i want to add on my skin , somthing like that:

https://github.com/Scrounger/MetrixReloaded/blob/master/screenshots/SecondInfoBar.jpg

This image or poster of event on second infobar,  here it's  poster about "Futurma"  event .

**Comment by Scrounger** [comment]
this image comes from epgshare plugin.
